import img4 from '../src/assets/images/download.jpg';
import img3 from '../src/assets/images/loginbackground.jpg';

// "#E50914"
export interface Episode {
  id: number;
  title: string;
  duration: string;
  date: string;
  image: string;
  year: number;
  starRating: number;
  desc: string;
  director: string; // Added director field
  main_lead: string; // Added main lead field
  streaming_platform: string; // Added streaming platform field
}

export const topRated: Episode[] = [
  {
    id: 1,
    title: "Ishaani Ishaani faces intense pressure",
    duration: "32m",
    date: "24 Apr",
    image: img3,
    year: 2023,
    starRating: 4.5,
    desc: "Ishaani faces intense pressure as she navigates personal and professional challenges. Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.Ishaani faces intense pressure as she navigates personal and professional challenges.",
    director: "Anjali Sharma",
    main_lead: "Priya Kapoor",
    streaming_platform: "Netflix",
  },
  {
    id: 2,
    title: "Armaan",
    duration: "21m",
    date: "24 Apr",
    image: img4,
    year: 2024,
    starRating: 3.8,
    desc: "Tensions rise as Armaan loses his temper with Ruhi in a dramatic confrontation.",
    director: "Rohan Mehta",
    main_lead: "Vikram Singh",
    streaming_platform: "Amazon Prime",
  },
  {
    id: 3,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img3,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
    director: "Sanjay Gupta",
    main_lead: "Aryan Khanna",
    streaming_platform: "Disney+ Hotstar",
  },
  {
    id: 4,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
    director: "Neha Kapoor",
    main_lead: "Riya Sharma",
    streaming_platform: "Zee5",
  },
  {
    id: 5,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img3,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
    director: "Sanjay Gupta",
    main_lead: "Aryan Khanna",
    streaming_platform: "Disney+ Hotstar",
  },
  {
    id: 6,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
    director: "Neha Kapoor",
    main_lead: "Riya Sharma",
    streaming_platform: "Zee5",
  },
  {
    id: 7,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img3,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
    director: "Sanjay Gupta",
    main_lead: "Aryan Khanna",
    streaming_platform: "Disney+ Hotstar",
  },
  {
    id: 8,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
    director: "Neha Kapoor",
    main_lead: "Riya Sharma",
    streaming_platform: "Zee5",
  },
];

export const hollywood: Episode[] = [
  {
    id: 1,
    title: "Ishaani Under Pressure",
    duration: "32m",
    date: "24 Apr",
    image: img3,
    year: 2023,
    starRating: 4.5,
    desc: "Ishaani faces intense pressure as she navigates personal and professional challenges.",
    director: "Christopher Nolan",
    main_lead: "Emma Stone",
    streaming_platform: "HBO Max",
  },
  {
    id: 2,
    title: "Armaan Snaps at Ruhi",
    duration: "21m",
    date: "24 Apr",
    image: img4,
    year: 2024,
    starRating: 3.8,
    desc: "Tensions rise as Armaan loses his temper with Ruhi in a dramatic confrontation.",
    director: "Greta Gerwig",
    main_lead: "Timothée Chalamet",
    streaming_platform: "Netflix",
  },
  {
    id: 3,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img3,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
    director: "James Cameron",
    main_lead: "Chris Pratt",
    streaming_platform: "Disney+",
  },
  {
    id: 4,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
    director: "Denis Villeneuve",
    main_lead: "Zendaya",
    streaming_platform: "Amazon Prime",
  },
  {
    id: 5,
    title: "Space Odyssey",
    duration: "40m",
    date: "20 Apr",
    image: img4,
    year: 2021,
    starRating: 4.7,
    desc: "An epic journey through the cosmos with breathtaking visuals.",
    director: "Alfonso Cuarón",
    main_lead: "Ryan Gosling",
    streaming_platform: "HBO Max",
  },
  {
    id: 6,
    title: "The Hero's Journey",
    duration: "35m",
    date: "21 Apr",
    image: img3,
    year: 2022,
    starRating: 3.5,
    desc: "A young hero embarks on a quest to save his world.",
    director: "Patty Jenkins",
    main_lead: "Tom Holland",
    streaming_platform: "Disney+",
  },
  {
    id: 7,
    title: "Cyber Heist",
    duration: "30m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.1,
    desc: "A thrilling cybercrime adventure with high stakes.",
    director: "Michael Bay",
    main_lead: "Scarlett Johansson",
    streaming_platform: "Netflix",
  },
  {
    id: 8,
    title: "Apocalypse Dawn",
    duration: "50m",
    date: "23 Apr",
    image: img3,
    year: 2024,
    starRating: 4.8,
    desc: "Survivors band together in a post-apocalyptic world.",
    director: "George Miller",
    main_lead: "Charlize Theron",
    streaming_platform: "HBO Max",
  },
  {
    id: 9,
    title: "Apocalypse Dawn",
    duration: "50m",
    date: "23 Apr",
    image: img3,
    year: 2024,
    starRating: 4.8,
    desc: "Survivors band together in a post-apocalyptic world.",
    director: "George Miller",
    main_lead: "Charlize Theron",
    streaming_platform: "HBO Max",
  },
];

export const bollywood: Episode[] = [
  {
    id: 9,
    title: "Dil Se Dil Tak",
    duration: "25m",
    date: "24 Apr",
    image: img3,
    year: 2023,
    starRating: 4.3,
    desc: "A heartfelt love story that transcends all obstacles.",
    director: "Karan Johar",
    main_lead: "Alia Bhatt",
    streaming_platform: "Netflix",
  },
  {
    id: 10,
    title: "Pyaar Ka Safar",
    duration: "22m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 3.9,
    desc: "A romantic journey filled with emotional highs and lows.",
    director: "Aditya Chopra",
    main_lead: "Ranbir Kapoor",
    streaming_platform: "Amazon Prime",
  },
  {
    id: 11,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img3,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
    director: "Sanjay Leela Bhansali",
    main_lead: "Deepika Padukone",
    streaming_platform: "Disney+ Hotstar",
  },
  {
    id: 12,
    title: "Rishtey",
    duration: "30m",
    date: "21 Apr",
    image: img4,
    year: 2023,
    starRating: 4.2,
    desc: "Exploring the complexities of relationships in modern India.",
    director: "Zoya Akhtar",
    main_lead: "Ranveer Singh",
    streaming_platform: "Zee5",
  },
  {
    id: 13,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img3,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
    director: "Sanjay Leela Bhansali",
    main_lead: "Deepika Padukone",
    streaming_platform: "Disney+ Hotstar",
  },
];